services:
  postgres:
    image: postgres:15
    container_name: novel-postgres
    restart: always
    environment:
      POSTGRES_DB: novel_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
